[package]
name = "blenb"
version = "0.1.0"
authors = ["Lucas Bittencourt (lbittencs@gmail.com)"]
edition = "2018"

[dependencies]
num = "0.2.0"
byteorder = "1.3.1"
derivative = "1.0.2"
nom = "4.2.3"
linked-hash-map = "0.5.2"
