cargo-features = ["profile-overrides"]

[workspace]
members = ["clever", "common", "client", "server", "blenb"] 

[profile.dev.overrides."*"]
opt-level = 2

#profile.dev.overrides.client]
#opt-level = 0