[package]
name = "blend"
version = "0.6.0"
authors = ["Lucas Bittencourt <lbittencs@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.0.0"
linked-hash-map = "0.5.2"
byteorder = "1.3.2"

[dev-dependencies]
libflate = "0.1"
walkdir = "2"